version: '3'
services:
  backend:
    image: ev-image
    build: .
    container_name: express-vote
    restart: always
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/express-vote-db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
    networks:
      - ev-network
    command: sh -c "yarn install && yarn dev"

  db:
    image: mongo:3.4
    container_name: ev-mongodb
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ev-network

networks:
  ev-network:

volumes:
  db-data:
